# Generated by Django 3.0.6 on 2020-05-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
