
// state:
// -CONVERSATIONs:
//     -byId
//     -order
//     -isFetching
//     -error

export const FETCH_CONVERSATIONS_STARTED = 'FETCH_CONVERSATIONS_STARTED';
export const FETCH_CONVERSATIONS_COMPLETED = 'FETCH_CONVERSATIONS_COMPLETED';
export const FETCH_CONVERSATIONS_FAILED = 'FETCH_CONVERSATIONS_FAILED';

export const ADD_CONVERSATION_STARTED = 'ADD_CONVERSATION_STARTED';
export const ADD_CONVERSATION_COMPLETED = 'ADD_CONVERSATION_COMPLETED';
export const ADD_CONVERSATION_FAILED = 'ADD_CONVERSATION_FAILED';

export const REMOVE_CONVERSATION_STARTED = 'REMOVE_CONVERSATION_STARTED';
export const REMOVE_CONVERSATION_COMPLETED = 'REMOVE_CONVERSATION_COMPLETED';
export const REMOVE_CONVERSATION_FAILED = 'REMOVE_CONVERSATION_FAILED';
