export const SIGN_UP_TUTOR_STARTED = "SIGN_UP_STARTED";
export const SIGN_UP_TUTOR_COMPLETED = "SIGN_UP_COMPLETED";
export const SIGN_UP_TUTOR_FAILED = "SIGN_UP_FAILED";
export const SIGN_UP_TUTOR_STEP_ONE = "SIGN_UP_TUTOR_STEP_ONE";