/*
State:
{
    Favoritos:[tutor1, tutor2, tutor3...] max 10
    Recomendados:[tutor1, tutor2, tutor3...] max 30
}
*/ 
export const FETCH_FAVORITE_TUTORS_STARTED = "_FAVORITE_TUTORS_STARTED";
export const FETCH_FAVORITE_TUTORS_COMPLETED = "_FAVORITE_TUTORS_COMPLETED";
export const FETCH_FAVORITE_TUTORS_FAILED = "_FAVORITE_TUTORS_FAILED";

export const ADD_FAVORITE_TUTOR_STARTED = "ADD_TO_FAVORITE_TUTOR_STARTED";
export const ADD_FAVORITE_TUTOR_COMPLETED = "ADD_TO_FAVORITE_TUTOR_COMPLETED";
export const ADD_FAVORITE_TUTOR_FAILED = "ADD_TO_FAVORITE_TUTOR_FAILED";

export const REMOVE_FAVORITE_TUTOR_STARTED = "REMOVE_FAVORITE_TUTOR_STARTED";
export const REMOVE_FAVORITE_TUTOR_COMPLETED = "REMOVE_FAVORITE_TUTOR_COMPLETED";
export const REMOVE_FAVORITE_TUTOR_FAILED = "REMOVE_FAVORITE_TUTOR_FAILED";

/*
export const CHAT_TUTOR = "CHAT_TUTOR";
export const VIEW_TUTOR = "VIEW_TUTOR";
*/ 
