/*
State:
{
    Favoritos:[tutor1, tutor2, tutor3...] max 10
    Recomendados:[tutor1, tutor2, tutor3...] max 30
}
*/ 
export const GET_FAVORITE_TUTORS_STARTED = "GET_FAVORITE_TUTORS_STARTED";
export const GET_FAVORITE_TUTORS_COMPLETED = "GET_FAVORITE_TUTORS_COMPLETED";
export const GET_FAVORITE_TUTORS_FAILED = "GET_FAVORITE_TUTORS_FAILED";

export const ADD_FAVORITE_TUTOR_STARTED = "ADD_TO_FAVORITE_TUTOR_STARTED";
export const ADD_FAVORITE_TUTOR_COMPLETED = "ADD_TO_FAVORITE_TUTOR_COMPLETED";
export const ADD_FAVORITE_TUTOR_FAILED = "ADD_TO_FAVORITE_TUTOR_FAILED";

export const DELETE_FAVORITE_TUTOR_STARTED = "DELETE_FAVORITE_TUTOR_STARTED";
export const DELETE_FAVORITE_TUTOR_COMPLETED = "DELETE_FAVORITE_TUTOR_COMPLETED";
export const DELETE_FAVORITE_TUTOR_FAILED = "DELETE_FAVORITE_TUTOR_FAILED";

/*
export const CHAT_TUTOR = "CHAT_TUTOR";
export const VIEW_TUTOR = "VIEW_TUTOR";
*/ 
