# Generated by Django 3.0.7 on 2020-11-06 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201003_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='birthdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
