# Generated by Django 3.0.6 on 2020-05-11 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='next',
        ),
        migrations.RemoveField(
            model_name='status',
            name='prev',
        ),
    ]
