from django.http import JsonResponse
from django.contrib.auth.models import User
from users.models import UserDetail
from institutions.models import Institution, Career, Course
from subjects.models import Subject, Topic
from locations.models import Location, Language
from schedules.models import Schedule, Period
from tutorias.models import Tutor, Tutoria
from workflows.models import Workflow, Status
from notifications.models import Notification

def create_initial_data(request):
    #LOCATION:
    #Continent:
    america = Location(name="America", location_type="continent")
    america.save()
    europa = Location(name="Europe", location_type="continent")
    europa.save()
    africa = Location(name="Africa", location_type="continent")
    africa.save()
    asia = Location(name="Asia", location_type="continent")
    asia.save()
    australia = Location(name="Australia", location_type="continent")
    australia.save()
    antarctica = Location(name="Antarctica", location_type="continent")
    antarctica.save()
    print('Continents done!')

    #Country:
    guate = Location(name="Guatemala", shortname="GT", code= 502, location_type="country", parent=america)
    guate.save()
    print('Countries done!')

    #Departamento/State
    gtDep = Location(name="Guatemala", location_type="department", parent=guate)
    gtDep.save()
    peten = Location(name="Petén", location_type="department", parent=guate)
    peten.save()
    huehue = Location(name="Huehuetenango", location_type="department", parent=guate)
    huehue.save()
    quiche = Location(name="Quiché", location_type="department", parent=guate)
    quiche.save()
    altavrpz = Location(name="Alta Verapaz", location_type="department", parent=guate)
    altavrpz.save()
    bajavrpz = Location(name="Baja verapaz", location_type="department", parent=guate)
    bajavrpz.save()
    izabal = Location(name="Izabal", location_type="department", parent=guate)
    izabal.save()
    sanmarcos = Location(name="San Marcos", location_type="department", parent=guate)
    sanmarcos.save()
    toto = Location(name="Totonicapán", location_type="department", parent=guate)
    toto.save()
    quetzal = Location(name="Quetzaltenango", location_type="department", parent=guate)
    quetzal.save()
    retalhuleu = Location(name="Retalhuleu", location_type="department", parent=guate)
    retalhuleu.save()
    suchi = Location(name="Suchitepéquez", location_type="department", parent=guate)
    suchi.save()
    solo = Location(name="Sololá", location_type="department", parent=guate)
    solo.save()
    progreso = Location(name="El Progreso", location_type="department", parent=guate)
    progreso.save()
    zacapa = Location(name="Zacapa", location_type="department", parent=guate)
    zacapa.save()
    chiqui= Location(name="Chiquimula", location_type="department", parent=guate)
    chiqui.save()
    jutiapa= Location(name="Jutiapa", location_type="department", parent=guate)
    jutiapa.save()
    strosa= Location(name="Santa Rosa", location_type="department", parent=guate)
    strosa.save()
    jalapa= Location(name="Jalapa", location_type="department", parent=guate)
    jalapa.save()
    chimal= Location(name="Chimaltenango", location_type="department", parent=guate)
    chimal.save()
    sacatpqz= Location(name="Sacatepéquez", location_type="department", parent=guate)
    sacatpqz.save()
    escuintla= Location(name="Escuintla", location_type="department", parent=guate)
    escuintla.save()
    print('Departments done!')
    #Municipio
    #Alta Verapaz
    chahal= Location(name='Chahal',location_type= 'municipality',parent= altavrpz)
    chahal.save()
    chisec= Location(name='Chisec',location_type= 'municipality',parent= altavrpz)
    chisec.save()
    coban= Location(name='Cobán',location_type= 'municipality',parent= altavrpz)
    coban.save()
    brtlmecss= Location(name='Fray Bartolomé de las Casas',location_type= 'municipality',parent= altavrpz)
    brtlmecss.save()
    tinta= Location(name='La Tinta',location_type= 'municipality',parent= altavrpz)
    tinta.save()
    lanquin= Location(name='Lanquín',location_type= 'municipality',parent= altavrpz)
    lanquin.save()
    panzos= Location(name='Panzós',location_type= 'municipality',parent= altavrpz)
    panzos.save()
    raxruha= Location(name='Raxruhá',location_type= 'municipality',parent= altavrpz)
    raxruha.save()
    sncrisVrpz= Location(name='San Cristóbal Verapaz',location_type= 'municipality',parent= altavrpz)
    sncrisVrpz.save()
    snjnchmlco= Location(name='San Juan Chamelco',location_type= 'municipality',parent= altavrpz)
    snjnchmlco.save()
    snpedrocarcha= Location(name='San Pedro Carchá' ,location_type= 'municipality',parent= altavrpz)
    snpedrocarcha.save()
    stcruzVrpz= Location(name='Santa Cruz Verapaz',location_type= 'municipality',parent= altavrpz)
    stcruzVrpz.save()
    sntmariacbon= Location(name='Santa María Cahabón',location_type= 'municipality',parent= altavrpz)
    sntmariacbon.save()
    senahu= Location(name='Senahú',location_type= 'municipality',parent= altavrpz)
    senahu.save()
    tamahu= Location(name='Tamahú',location_type= 'municipality',parent= altavrpz)
    tamahu.save()
    tactic= Location(name='Tactic',location_type= 'municipality',parent= altavrpz)
    tactic.save()
    tucuru= Location(name='Tucurú',location_type= 'municipality',parent= altavrpz)
    tucuru.save()
    print('Municipalities Alta Verapaz done!')

    #Baja Verapaz
    cubulco= Location(name='Cubulco' ,location_type= 'municipality',parent= bajavrpz)
    cubulco.save()
    granados= Location(name='Granados',location_type= 'municipality',parent= bajavrpz)
    granados.save()
    purulha= Location(name='Purulhá' ,location_type= 'municipality',parent= bajavrpz)
    purulha.save()
    rabinal= Location(name='Rabinal' ,location_type= 'municipality',parent= bajavrpz)
    rabinal.save()
    salama= Location(name='Salamá'    ,location_type= 'municipality',parent= bajavrpz)
    salama.save()
    snjeronimo= Location(name='San Jerónimo',location_type= 'municipality',parent= bajavrpz)
    snjeronimo.save()
    snmiguelchicaj= Location(name='San Miguel Chicaj' ,location_type= 'municipality',parent= bajavrpz)
    snmiguelchicaj.save()
    sntcruzchol= Location(name='Santa Cruz el Chol',location_type= 'municipality',parent= bajavrpz)
    sntcruzchol.save()
    print('Municipalities Baja Verapaz done!')

    #Chimaltenango
    acatenango= Location(name='Acatenango',location_type= 'municipality',parent= chimal)
    acatenango.save()
    chimaltenago= Location(name='Chimaltenango',location_type= 'municipality',parent= chimal)
    chimaltenago.save()
    tejar= Location(name='El Tejar',location_type= 'municipality',parent= chimal)
    tejar.save()
    parramos= Location(name='Parramos',location_type= 'municipality',parent= chimal)
    parramos.save()
    patzicia= Location(name='Patzicía',location_type= 'municipality',parent= chimal)
    patzicia.save()
    patzun= Location(name='Patzún',location_type= 'municipality',parent= chimal)
    patzun.save()
    pochuta= Location(name='Pochuta',location_type= 'municipality',parent= chimal)
    pochuta.save()
    snndresitzpa= Location(name='San Andrés Itzapa',location_type= 'municipality',parent= chimal)
    snndresitzpa.save()
    snjosepoaquil= Location(name='San José Poaquíl' ,location_type= 'municipality',parent= chimal)
    snjosepoaquil.save()
    snjuancmlpa= Location(name='San Juan Comalapa',location_type= 'municipality',parent= chimal)
    snjuancmlpa.save()
    snmrtnjlotpq= Location(name='San Martín Jilotepeque',location_type= 'municipality',parent= chimal)
    snmrtnjlotpq.save()
    sntapolonia= Location(name='Santa Apolonia',location_type= 'municipality',parent= chimal)
    sntapolonia.save()
    sntcrzblanya= Location(name='Santa Cruz Balanyá' ,location_type= 'municipality',parent= chimal)
    sntcrzblanya.save()
    tecpan= Location(name='Tecpán',location_type= 'municipality',parent= chimal)
    tecpan.save()
    yepocapa= Location(name='Yepocapa' ,location_type= 'municipality',parent= chimal)
    yepocapa.save()
    zaragoza= Location(name='Zaragoza',location_type= 'municipality',parent= chimal)
    zaragoza.save()
    print('Municipalities Chimaltenango done!')

    #Chiquimula
    camotan= Location(name='Camotán',location_type= 'municipality',parent= chiqui)
    camotan.save()
    chiquimula= Location(name='Chiquimula',location_type= 'municipality',parent= chiqui)
    chiquimula.save()
    cncpcionmnas= Location(name='Concepción Las Minas',location_type= 'municipality',parent= chiqui)
    cncpcionmnas.save()
    esquipulas= Location(name='Esquipulas',location_type= 'municipality',parent= chiqui)
    esquipulas.save()
    ipala= Location(name='Ipala',location_type= 'municipality',parent= chiqui)
    ipala.save()
    jocotan= Location(name='Jocotán',location_type= 'municipality',parent= chiqui)
    jocotan.save()
    olopa= Location(name='Olopa',location_type= 'municipality',parent= chiqui)
    olopa.save()
    qtzaltpq= Location(name='Quezaltepeque',location_type= 'municipality',parent= chiqui)
    qtzaltpq.save()
    snjacinto= Location(name='San Jacinto',location_type= 'municipality',parent= chiqui)
    snjacinto.save()
    snjosearada= Location(name='San José la Arada',location_type= 'municipality',parent= chiqui)
    snjosearada.save()
    snjnermita= Location(name='San Juan Ermita',location_type= 'municipality',parent= chiqui)
    snjnermita.save()
    print('Municipalities Chiquimula done!')

    #El Progreso
    jicaro= Location(name='El Jícaro',location_type= 'municipality',parent= progreso)
    jicaro.save()
    guastatoya= Location(name='Guastatoya',location_type= 'municipality',parent= progreso)
    guastatoya.save()
    morazan= Location(name='Morazán',location_type= 'municipality',parent= progreso)
    morazan.save()
    snagstinacsgstln= Location(name='San Agustín Acasaguastlán',location_type= 'municipality',parent= progreso)
    snagstinacsgstln.save()
    snantoniopz= Location(name='San Antonio La Paz',location_type= 'municipality',parent= progreso)
    snantoniopz.save()
    sncrisacsgtln= Location(name='San Cristóbal Acasaguastlán' ,location_type= 'municipality',parent= progreso)
    sncrisacsgtln.save()
    sanarate= Location(name='Sanarate',location_type= 'municipality',parent= progreso)
    sanarate.save()
    sansare= Location(name='Sansare',location_type= 'municipality',parent= progreso)
    sansare.save()
    print('Municipalities El Progreso done!')

    #Escuintla
    mescuintla= Location(name='Escuintla',location_type= 'municipality',parent= escuintla)
    mescuintla.save()
    guanagazapa= Location(name='Guanagazapa',location_type= 'municipality',parent= escuintla)
    guanagazapa.save()
    iztapa= Location(name='Iztapa',location_type= 'municipality',parent= escuintla)
    iztapa.save()
    democracia= Location(name='La Democracia',location_type= 'municipality',parent= escuintla)
    democracia.save()
    gomera= Location(name='La Gomera',location_type= 'municipality',parent= escuintla)
    gomera.save()
    masagua= Location(name='Masagua',location_type= 'municipality',parent= escuintla)
    masagua.save()
    nvconcepcion= Location(name='Nueva Concepción',location_type= 'municipality',parent= escuintla)
    nvconcepcion.save()
    palin= Location(name='Palín',location_type= 'municipality',parent= escuintla)
    palin.save()
    snjose= Location(name='San José',location_type= 'municipality',parent= escuintla)
    snjose.save()
    snvcntepcya= Location(name='San Vicente Pacaya',location_type= 'municipality',parent= escuintla)
    snvcntepcya.save()
    sntaluciactzmlgpa= Location(name='Santa Lucía Cotzumalguapa',location_type= 'municipality',parent= escuintla)
    sntaluciactzmlgpa.save()
    siquinala= Location(name='Siquinalá',location_type= 'municipality',parent= escuintla)
    siquinala.save()
    tiquisate= Location(name='Tiquisate',location_type= 'municipality',parent= escuintla)
    tiquisate.save()
    print('Municipalities Escuintla done!')

    #Guatemala
    amatitlan= Location(name='Amatitlán',location_type= 'municipality',parent= gtDep)
    amatitlan.save()
    chinautla= Location(name='Chinautla',location_type= 'municipality',parent= gtDep)
    chinautla.save()
    chuarracho= Location(name='Chuarrancho',location_type= 'municipality',parent= gtDep)
    chuarracho.save()
    mguatemala= Location(name='Guatemala',location_type= 'municipality',parent= gtDep)
    mguatemala.save()
    mfraijanes= Location(name='Fraijanes',location_type= 'municipality',parent= gtDep)
    mfraijanes.save()
    mixco= Location(name='Mixco',location_type= 'municipality',parent= gtDep)
    mixco.save()
    palencia= Location(name='Palencia',location_type= 'municipality',parent= gtDep)
    palencia.save()
    snjosedlgolfo= Location(name='San José del Golfo',location_type= 'municipality',parent= gtDep)
    snjosedlgolfo.save()
    snjosepnla= Location(name='San José Pinula' ,location_type= 'municipality',parent= gtDep)
    snjosepnla.save()
    snjnsctpqz= Location(name='San Juan Sacatepéquez',location_type= 'municipality',parent= gtDep)
    snjnsctpqz.save()
    snmiguelptp= Location(name='San Miguel Petapa',location_type= 'municipality',parent= gtDep)
    snmiguelptp.save()
    snpedroayampuc= Location(name='San Pedro Ayampuc',location_type= 'municipality',parent= gtDep)
    snpedroayampuc.save()
    snpedrosctpqz= Location(name='San Pedro Sacatepéquez',location_type= 'municipality',parent= gtDep)
    snpedrosctpqz.save()
    snrymndo= Location(name='San Raymundo',location_type= 'municipality',parent= gtDep)
    snrymndo.save()
    sntcatarinapnla= Location(name='Santa Catarina Pinula',location_type= 'municipality',parent= gtDep)
    sntcatarinapnla.save()
    villacnles= Location(name='Villa Canales',location_type= 'municipality',parent= gtDep)
    villacnles.save()
    villanva= Location(name='Villa Nueva',location_type= 'municipality',parent= gtDep)
    villanva.save()
    print('Municipalities Guatemala done!')

    #Huehuetenango
    aguacatan= Location(name='Aguacatán',location_type= 'municipality',parent= huehue)
    aguacatan.save()
    chiantla= Location(name='Chiantla' ,location_type= 'municipality',parent= huehue)
    chiantla.save()
    colotenango= Location(name='Colotenango' ,location_type= 'municipality',parent= huehue)
    colotenango.save()
    cncpcionhsta= Location(name='Concepción Huista',location_type= 'municipality',parent= huehue)
    cncpcionhsta.save()
    cuilco= Location(name='Cuilco',location_type= 'municipality',parent= huehue)
    cuilco.save()
    huehuetng= Location(name='Huehuetenango',location_type= 'municipality',parent= huehue)
    huehuetng.save()
    jacaltenango= Location(name='Jacaltenango',location_type= 'municipality',parent= huehue)
    jacaltenango.save()
    ldemocracia= Location(name='La Democracia',location_type= 'municipality',parent= huehue)
    ldemocracia.save()
    libertad= Location(name='La Libertad' ,location_type= 'municipality',parent= huehue)
    libertad.save()
    malacatancito= Location(name='Malacatancito',location_type= 'municipality',parent= huehue)
    malacatancito.save()
    nenton= Location(name='Nentón',location_type= 'municipality',parent= huehue)
    nenton.save()
    snantoniohsta= Location(name='San Antonio Huista',location_type= 'municipality',parent= huehue)
    snantoniohsta.save()
    sngasparixchl= Location(name='San Gaspar Ixchil',location_type= 'municipality',parent= huehue)
    sngasparixchl.save()
    snildfonsoixtahca= Location(name='San Ildefonso Ixtahuacán',location_type= 'municipality',parent= huehue)
    snildfonsoixtahca.save()
    snjnatitn= Location(name='San Juan Atitán',location_type= 'municipality',parent= huehue)
    snjnatitn.save()
    snjnixcoy= Location(name='San Juan Ixcoy',location_type= 'municipality',parent= huehue)
    snjnixcoy.save()
    snmteoixttn= Location(name='San Mateo Ixtatán',location_type= 'municipality',parent= huehue)
    snmteoixttn.save()
    snmiguelactan= Location(name='San Miguel Acatán',location_type= 'municipality',parent= huehue)
    snmiguelactan.save()
    snpedronecta= Location(name='San Pedro Nécta',location_type= 'municipality',parent= huehue)
    snpedronecta.save()
    snpedroslma= Location(name='San Pedro Soloma' ,location_type= 'municipality',parent= huehue)
    snpedroslma.save()
    snrfllaindpndncia= Location(name='San Rafael La Independencia',location_type= 'municipality',parent= huehue)
    snrfllaindpndncia.save()
    snrflptzal= Location(name='San Rafael Pétzal',location_type= 'municipality',parent= huehue)
    snrflptzal.save()
    snsbstiancoatan= Location(name='San Sebastián Coatán',location_type= 'municipality',parent= huehue)
    snsbstiancoatan.save()
    snbstianhuehue= Location(name='San Sebastián Huehuetenango',location_type= 'municipality',parent= huehue)
    snbstianhuehue.save()
    sntanahsta= Location(name='Santa Ana Huista',location_type= 'municipality',parent= huehue)
    sntanahsta.save()
    sntbarbara= Location(name='Santa Bárbara',location_type= 'municipality',parent= huehue)
    sntbarbara.save()
    sntcrzbrillas= Location(name='Santa Cruz Barillas',location_type= 'municipality',parent= huehue)
    sntcrzbrillas.save()
    snteulalia= Location(name='Santa Eulalia',location_type= 'municipality',parent= huehue)
    snteulalia.save()
    sntiagochiml= Location(name='Santiago Chimaltenango',location_type= 'municipality',parent= huehue)
    sntiagochiml.save()
    tecticn= Location(name='Tectitán',location_type= 'municipality',parent= huehue)
    tecticn.save()
    tdssntscuchu= Location(name='Todos Santos Cuchumatán',location_type= 'municipality',parent= huehue)
    tdssntscuchu.save()
    uncntinil= Location(name='Unión Cantinil',location_type= 'municipality',parent= huehue)
    uncntinil.save()
    print('Municipalities Huehuetenango done!')

    #Izabal
    lestor= Location(name='El Estor',location_type= 'municipality',parent= izabal)
    lestor.save()
    livingston= Location(name='Livingston',location_type= 'municipality',parent= izabal)
    livingston.save()
    lsamates= Location(name='Los Amates',location_type= 'municipality',parent= izabal)
    lsamates.save()
    morales= Location(name='Morales',location_type= 'municipality',parent= izabal)
    morales.save()
    prtobarrios= Location(name='Puerto Barrios',location_type= 'municipality',parent= izabal)
    prtobarrios.save()
    print('Municipalities Izabal done!')

    #Jalapa
    mjalapa= Location(name='Jalapa',location_type= 'municipality',parent= jalapa)
    mjalapa.save()
    mtquescuintla= Location(name='Mataquescuintla',location_type= 'municipality',parent= jalapa)
    mtquescuintla.save()
    monjas= Location(name='Monjas',location_type= 'municipality',parent= jalapa)
    monjas.save()
    sncrlsalztate= Location(name='San Carlos Alzatate',location_type= 'municipality',parent= jalapa)
    sncrlsalztate.save()
    snlsjltpq= Location(name='San Luis Jilotepeque',location_type= 'municipality',parent= jalapa)
    snlsjltpq.save()
    snmnlchpron= Location(name='San Manuel Chaparrón',location_type= 'municipality',parent= jalapa)
    snmnlchpron.save()
    snpedropnla= Location(name='San Pedro Pinula',location_type= 'municipality',parent= jalapa)
    snpedropnla.save()
    print('Municipalities Jalapa done!')

    #Jutiapa
    aguanca= Location(name='Agua nca',location_type= 'municipality',parent= jutiapa)
    aguanca.save()
    asncionmta= Location(name='Asunción Mita',location_type= 'municipality',parent= jutiapa)
    asncionmta.save()
    atsctmpa= Location(name='Atescatempa' ,location_type= 'municipality',parent= jutiapa)
    atsctmpa.save()
    comapa= Location(name='Comapa',location_type= 'municipality',parent= jutiapa)
    comapa.save()
    conguaco= Location(name='Conguaco',location_type= 'municipality',parent= jutiapa)
    conguaco.save()
    adelanto= Location(name='El Adelanto' ,location_type= 'municipality',parent= jutiapa)
    adelanto.save()
    mprogrso= Location(name='El Progreso' ,location_type= 'municipality',parent= jutiapa)
    mprogrso.save()
    jlptagua= Location(name='Jalpatagua',location_type= 'municipality',parent= jutiapa)
    jlptagua.save()
    jerez= Location(name='Jerez',location_type= 'municipality',parent= jutiapa)
    jerez.save()
    jtiapa= Location(name='Jutiapa',location_type= 'municipality',parent= jutiapa)
    jtiapa.save()
    myuta= Location(name='Moyuta',location_type= 'municipality',parent= jutiapa)
    myuta.save()
    pasaco= Location(name='Pasaco',location_type= 'municipality',parent= jutiapa)
    pasaco.save()
    quesada= Location(name='Quesada' ,location_type= 'municipality',parent= jutiapa)
    quesada.save()
    snjoseactempa= Location(name='San José Acatempa',location_type= 'municipality',parent= jutiapa)
    snjoseactempa.save()
    sntactrinamita= Location(name='Santa Catarina Mita',location_type= 'municipality',parent= jutiapa)
    sntactrinamita.save()
    yupltepeque= Location(name='Yupiltepeque',location_type= 'municipality',parent= jutiapa)
    yupltepeque.save()
    zapotitlan= Location(name='Zapotitlán',location_type= 'municipality',parent= jutiapa)
    zapotitlan.save()
    print('Municipalities Jutiapa done!')

    #Petén
    dolores= Location(name='Dolores',location_type= 'municipality',parent= peten)
    dolores.save()
    chal= Location(name='El Chal',location_type= 'municipality',parent= peten)
    chal.save()
    cdflores= Location(name='Ciudad Flores',location_type= 'municipality',parent= peten)
    cdflores.save()
    lalibertad= Location(name='La Libertad',location_type= 'municipality',parent= peten)
    lalibertad.save()
    lascrces= Location(name='Las Cruces',location_type= 'municipality',parent= peten)
    lascrces.save()
    melchrdmncos= Location(name='Melchor de Mencos',location_type= 'municipality',parent= peten)
    melchrdmncos.save()
    pptun= Location(name='Poptún',location_type= 'municipality',parent= peten)
    pptun.save()
    snandres= Location(name='San Andrés',location_type= 'municipality',parent= peten)
    snandres.save()
    snbenito= Location(name='San Benito',location_type= 'municipality',parent= peten)
    snbenito.save()
    snfrancisco= Location(name='San Francisco',location_type= 'municipality',parent= peten)
    snfrancisco.save()
    snjoseptn= Location(name='San José',location_type= 'municipality',parent= peten)
    snjoseptn.save()
    snluis= Location(name='San Luis' ,location_type= 'municipality',parent= peten)
    snluis.save()
    sntana= Location(name='Santa Ana',location_type= 'municipality',parent= peten)
    sntana.save()
    sayaxche= Location(name='Sayaxché' ,location_type= 'municipality',parent= peten)
    sayaxche.save()
    print('Municipalities Peten done!')

    #Quetzaltenango
    almolonga= Location(name='Almolonga',location_type= 'municipality',parent= quetzal)
    almolonga.save()
    cabrican= Location(name='Cabricán',location_type= 'municipality',parent= quetzal)
    cabrican.save()
    cojola= Location(name='Cajolá',location_type= 'municipality',parent= quetzal)
    cojola.save()
    cantel= Location(name='Cantel',location_type= 'municipality',parent= quetzal)
    cantel.save()
    coatepeque= Location(name='Coatepeque',location_type= 'municipality',parent= quetzal)
    coatepeque.save()
    clombacstacuca= Location(name='Colomba Costa Cuca',location_type= 'municipality',parent= quetzal)
    clombacstacuca.save()
    cncpcionchqrichapa= Location(name='Concepción Chiquirichapa',location_type= 'municipality',parent= quetzal)
    cncpcionchqrichapa.save()
    lpalmar= Location(name='El Palmar',location_type= 'municipality',parent= quetzal)
    lpalmar.save()
    flrescstacuca= Location(name='Flores Costa Cuca',location_type= 'municipality',parent= quetzal)
    flrescstacuca.save()
    genova= Location(name='Génova',location_type= 'municipality',parent= quetzal)
    genova.save()
    huitan= Location(name='Huitán',location_type= 'municipality',parent= quetzal)
    huitan.save()
    laesperanza= Location(name='La Esperanza',location_type= 'municipality',parent= quetzal)
    laesperanza.save()
    olintepeque= Location(name='Olintepeque',location_type= 'municipality',parent= quetzal)
    olintepeque.save()
    plestinadlaltos= Location(name='Palestina de Los Altos' ,location_type= 'municipality',parent= quetzal)
    plestinadlaltos.save()
    qtzltnango= Location(name='Quetzaltenango',location_type= 'municipality',parent= quetzal)
    qtzltnango.save()
    salcja= Location(name='Salcajá',location_type= 'municipality',parent= quetzal)
    salcja.save()
    sncrlsija= Location(name='San Carlos Sija',location_type= 'municipality',parent= quetzal)
    sncrlsija.save()
    snfrnciscolunion= Location(name='San Francisco La Unión',location_type= 'municipality',parent= quetzal)
    snfrnciscolunion.save()
    snjnosnclco= Location(name='San Juan Ostuncalco',location_type= 'municipality',parent= quetzal)
    snjnosnclco.save()
    snmrtinsctpequez= Location(name='San Martín Sacatepéquez',location_type= 'municipality',parent= quetzal)
    snmrtinsctpequez.save()
    snmateo= Location(name='San Mateo',location_type= 'municipality',parent= quetzal)
    snmateo.save()
    snmguelsguila= Location(name='San Miguel Sigüilá',location_type= 'municipality',parent= quetzal)
    snmguelsguila.save()
    sibilia= Location(name='Sibilia',location_type= 'municipality',parent= quetzal)
    sibilia.save()
    zunil= Location(name='Zunil',location_type= 'municipality',parent= quetzal)
    zunil.save()
    print('Municipalities Quetzaltenango done!')

    #Quiché
    canilla= Location(name='Canillá' ,location_type= 'municipality',parent= quiche)
    canilla.save()
    chajul= Location(name='Chajul',location_type= 'municipality',parent= quiche)
    chajul.save()
    chicaman= Location(name='Chicamán',location_type= 'municipality',parent= quiche)
    chicaman.save()
    chiche= Location(name='Chiché',location_type= 'municipality',parent= quiche)
    chiche.save()
    chichicstngo= Location(name='Chichicastenango',location_type= 'municipality',parent= quiche)
    chichicstngo.save()
    chinique= Location(name='Chinique',location_type= 'municipality',parent= quiche)
    chinique.save()
    cunen= Location(name='Cunén',location_type= 'municipality',parent= quiche)
    cunen.save()
    ixcnplyagrnd= Location(name='Ixcán Playa Grande' ,location_type= 'municipality',parent= quiche)
    ixcnplyagrnd.save()
    joyabaj= Location(name='Joyabaj',location_type= 'municipality',parent= quiche)
    joyabaj.save()
    nebaj= Location(name='Nebaj',location_type= 'municipality',parent= quiche)
    nebaj.save()
    pachalum= Location(name='Pachalum',location_type= 'municipality',parent= quiche)
    pachalum.save()
    patzite= Location(name='Patzité' ,location_type= 'municipality',parent= quiche)
    patzite.save()
    sacapulas= Location(name='Sacapulas',location_type= 'municipality',parent= quiche)
    sacapulas.save()
    sndresjcbja= Location(name='San Andrés Sajcabajá',location_type= 'municipality',parent= quiche)
    sndresjcbja.save()
    snantonioilotengo= Location(name='San Antonio Ilotenango',location_type= 'municipality',parent= quiche)
    snantonioilotengo.save()
    snbrtolomejoco= Location(name='San Bartolomé Jocotenango',location_type= 'municipality',parent= quiche)
    snbrtolomejoco.save()
    snjnctzal= Location(name='San Juan Cotzal',location_type= 'municipality',parent= quiche)
    snjnctzal.save()
    snpedrojoco= Location(name='San Pedro Jocopilas',location_type= 'municipality',parent= quiche)
    snpedrojoco.save()
    sntcruzdlquiche= Location(name='Santa Cruz del Quiché',location_type= 'municipality',parent= quiche)
    sntcruzdlquiche.save()
    uspatan= Location(name='Uspantán',location_type= 'municipality',parent= quiche)
    uspatan.save()
    zacualpa= Location(name='Zacualpa',location_type= 'municipality',parent= quiche)
    zacualpa.save()
    print('Municipalities Quiche done!')

    #Retalhuleu
    champerico= Location(name='Champerico',location_type= 'municipality',parent= retalhuleu)
    champerico.save()
    asintal= Location(name='El Asintal',location_type= 'municipality',parent= retalhuleu)
    asintal.save()
    nvsncrls= Location(name='Nuevo San Carlos',location_type= 'municipality',parent= retalhuleu)
    nvsncrls.save()
    rtlhleu= Location(name='Retalhuleu',location_type= 'municipality',parent= retalhuleu)
    rtlhleu.save()
    snandrsvllaseca= Location(name='San Andrés Villa Seca' ,location_type= 'municipality',parent= retalhuleu)
    snandrsvllaseca.save()
    snflpereu= Location(name='San Felipe Reu',location_type= 'municipality',parent= retalhuleu)
    snflpereu.save()
    snmrtinzptitlan= Location(name='San Martín Zapotitlán' ,location_type= 'municipality',parent= retalhuleu)
    snmrtinzptitlan.save()
    snsbastian= Location(name='San Sebastián',location_type= 'municipality',parent= retalhuleu)
    snsbastian.save()
    sntcrzmlua= Location(name='Santa Cruz Muluá' ,location_type= 'municipality',parent= retalhuleu)
    sntcrzmlua.save()
    print('Municipalities Retalhuleu done!')

    #Sacatepéquez
    alotenango= Location(name='Alotenango',location_type= 'municipality',parent= sacatpqz)
    alotenango.save()
    cddvieja= Location(name='Ciudad Vieja',location_type= 'municipality',parent= sacatpqz)
    cddvieja.save()
    jocotenango= Location(name='Jocotenango',location_type= 'municipality',parent= sacatpqz)
    jocotenango.save()
    antggt= Location(name='Antigua Guatemala',location_type= 'municipality',parent= sacatpqz)
    antggt.save()
    mgdlenamlpasaltas= Location(name='Magdalena Milpas Altas',location_type= 'municipality',parent= sacatpqz)
    mgdlenamlpasaltas.save()
    pstres= Location(name='Pastores',location_type= 'municipality',parent= sacatpqz)
    pstres.save()
    snantonioaguasclnts= Location(name='San Antonio Aguas Calientes' ,location_type= 'municipality',parent= sacatpqz)
    snantonioaguasclnts.save()
    snbartlmilpsalts= Location(name='San Bartolomé Milpas Altas',location_type= 'municipality',parent= sacatpqz)
    snbartlmilpsalts.save()
    snlcssctpqz= Location(name='San Lucas Sacatepéquez',location_type= 'municipality',parent= sacatpqz)
    snlcssctpqz.save()
    snmigueldas= Location(name='San Miguel Dueñas',location_type= 'municipality',parent= sacatpqz)
    snmigueldas.save()
    sntcatarinabrma= Location(name='Santa Catarina Barahona',location_type= 'municipality',parent= sacatpqz)
    sntcatarinabrma.save()
    sntlciamlpsalts= Location(name='Santa Lucía Milpas Altas',location_type= 'municipality',parent= sacatpqz)
    sntlciamlpsalts.save()
    sntmariadejss= Location(name='Santa María de Jesús',location_type= 'municipality',parent= sacatpqz)
    sntmariadejss.save()
    sntiagosctpqz= Location(name='Santiago Sacatepéquez',location_type= 'municipality',parent= sacatpqz)
    sntiagosctpqz.save()
    sntodmngxencoj= Location(name='Santo Domingo Xenacoj' ,location_type= 'municipality',parent= sacatpqz)
    sntodmngxencoj.save()
    sompango= Location(name='Sumpango',location_type= 'municipality',parent= sacatpqz)
    sompango.save()
    print('Municipalities Sacatepequez done!')

    #San Marcos
    ayutla= Location(name='Ayutla',location_type= 'municipality',parent= sanmarcos)
    ayutla.save()
    catarina= Location(name='Catarina',location_type= 'municipality',parent= sanmarcos)
    catarina.save()
    comitan= Location(name='Comitancillo',location_type= 'municipality',parent= sanmarcos)
    comitan.save()
    cncpcionttuapa= Location(name='Concepción Tutuapa',location_type= 'municipality',parent= sanmarcos)
    cncpcionttuapa.save()
    lquetzal= Location(name='El Quetzal',location_type= 'municipality',parent= sanmarcos)
    lquetzal.save()
    tumbador= Location(name='El Tumbador',location_type= 'municipality',parent= sanmarcos)
    tumbador.save()
    sqplasplogrdo= Location(name='Esquipulas Palo Gordo',location_type= 'municipality',parent= sanmarcos)
    sqplasplogrdo.save()
    ixchiguan= Location(name='Ixchiguán',location_type= 'municipality',parent= sanmarcos)
    ixchiguan.save()
    lnca= Location(name='La nca',location_type= 'municipality',parent= sanmarcos)
    lnca.save()
    lreforma= Location(name='La Reforma' ,location_type= 'municipality',parent= sanmarcos)
    lreforma.save()
    malacatan= Location(name='Malacatán',location_type= 'municipality',parent= sanmarcos)
    malacatan.save()
    nvprogreso= Location(name='Nuevo Progreso',location_type= 'municipality',parent= sanmarcos)
    nvprogreso.save()
    ocos= Location(name='Ocós',location_type= 'municipality',parent= sanmarcos)
    ocos.save()
    pajapita= Location(name='Pajapita',location_type= 'municipality',parent= sanmarcos)
    pajapita.save()
    rionco= Location(name='Río nco' ,location_type= 'municipality',parent= sanmarcos)
    rionco.save()
    sntoniosctpqz= Location(name='San Antonio Sacatepéquez',location_type= 'municipality',parent= sanmarcos)
    sntoniosctpqz.save()
    sncrscucho= Location(name='San Cristóbal Cucho',location_type= 'municipality',parent= sanmarcos)
    sncrscucho.save()
    snjserodeo= Location(name='San José El Rodeo',location_type= 'municipality',parent= sanmarcos)
    snjserodeo.save()
    snjseojetenam= Location(name='San José Ojetenam',location_type= 'municipality',parent= sanmarcos)
    snjseojetenam.save()
    snlrnzo= Location(name='San Lorenzo',location_type= 'municipality',parent= sanmarcos)
    snlrnzo.save()
    snmrcos= Location(name='San Marcos',location_type= 'municipality',parent= sanmarcos)
    snmrcos.save()
    snmguelixtahcan= Location(name='San Miguel Ixtahuacán',location_type= 'municipality',parent= sanmarcos)
    snmguelixtahcan.save()
    snpablo= Location(name='San Pablo',location_type= 'municipality',parent= sanmarcos)
    snpablo.save()
    snspedrosctpqz= Location(name='San Pedro Sacatepéquez',location_type= 'municipality',parent= sanmarcos)
    snspedrosctpqz.save()
    snrflpiedlcuesta= Location(name='San Rafael Pie de la Cuesta',location_type= 'municipality',parent= sanmarcos)
    snrflpiedlcuesta.save()
    sibinal= Location(name='Sibinal',location_type= 'municipality',parent= sanmarcos)
    sibinal.save()
    sipacapa= Location(name='Sipacapa',location_type= 'municipality',parent= sanmarcos)
    sipacapa.save()
    tacana= Location(name='Tacaná',location_type= 'municipality',parent= sanmarcos)
    tacana.save()
    tajumulco= Location(name='Tajumulco',location_type= 'municipality',parent= sanmarcos)
    tajumulco.save()
    tejutla= Location(name='Tejutla',location_type= 'municipality',parent= sanmarcos)
    tejutla.save()
    print('Municipalities San Marcos done!')

    #Santa Rosa
    baberena= Location(name='Barberena',location_type= 'municipality',parent= strosa)
    baberena.save()
    casillas= Location(name='Casillas',location_type= 'municipality',parent= strosa)
    casillas.save()
    chiquimulilla= Location(name='Chiquimulilla',location_type= 'municipality',parent= strosa)
    chiquimulilla.save()
    cuilapa= Location(name='Cuilapa',location_type= 'municipality',parent= strosa)
    cuilapa.save()
    guazacapan= Location(name='Guazacapán',location_type= 'municipality',parent= strosa)
    guazacapan.save()
    nvsntrosa= Location(name='Nueva Santa Rosa',location_type= 'municipality',parent= strosa)
    nvsntrosa.save()
    oratorio= Location(name='Oratorio',location_type= 'municipality',parent= strosa)
    oratorio.save()
    pblonvovinas= Location(name='Pueblo Nuevo Viñas',location_type= 'municipality',parent= strosa)
    pblonvovinas.save()
    snjntcuaco= Location(name='San Juan Tecuaco',location_type= 'municipality',parent= strosa)
    snjntcuaco.save()
    snrfllsflres= Location(name='San Rafael las Flores',location_type= 'municipality',parent= strosa)
    snrfllsflres.save()
    sntcrznarnjo= Location(name='Santa Cruz Naranjo',location_type= 'municipality',parent= strosa)
    sntcrznarnjo.save()
    sntamariaixhtan= Location(name='Santa María Ixhuatán' ,location_type= 'municipality',parent= strosa)
    sntamariaixhtan.save()
    sntarsalma= Location(name='Santa Rosa de Lima',location_type= 'municipality',parent= strosa)
    sntarsalma.save()
    taxisco= Location(name='Taxisco',location_type= 'municipality',parent= strosa)
    taxisco.save()
    print('Municipalities Santa Rosa done!')

    #Sololá
    concepcion= Location(name='Concepción',location_type= 'municipality',parent= solo)
    concepcion.save()
    nahuala= Location(name='Nahualá',location_type= 'municipality',parent= solo)
    nahuala.save()
    pana= Location(name='Panajachel',location_type= 'municipality',parent= solo)
    pana.save()
    snandressmtbj= Location(name='San Andrés Semetabaj',location_type= 'municipality',parent= solo)
    snandressmtbj.save()
    snntonioplopo= Location(name='San Antonio Palopó',location_type= 'municipality',parent= solo)
    snntonioplopo.save()
    snjsechcya= Location(name='San José Chacayá',location_type= 'municipality',parent= solo)
    snjsechcya.save()
    snjnlalguna= Location(name='San Juan La Laguna',location_type= 'municipality',parent= solo)
    snjnlalguna.save()
    snlucstoliman= Location(name='San Lucas Tolimán',location_type= 'municipality',parent= solo)
    snlucstoliman.save()
    snmarcosllguna= Location(name='San Marcos La Laguna',location_type= 'municipality',parent= solo)
    snmarcosllguna.save()
    snpblollaguna= Location(name='San Pablo La Laguna',location_type= 'municipality',parent= solo)
    snpblollaguna.save()
    snpdrollguna= Location(name='San Pedro La Laguna',location_type= 'municipality',parent= solo)
    snpdrollguna.save()
    sntactrinaixthcn= Location(name='Santa Catarina Ixtahuacán',location_type= 'municipality',parent= solo)
    sntactrinaixthcn.save()
    sntacatarnplpo= Location(name='Santa Catarina Palopó',location_type= 'municipality',parent= solo)
    sntacatarnplpo.save()
    sntclrallaguna= Location(name='Santa Clara La Laguna',location_type= 'municipality',parent= solo)
    sntclrallaguna.save()
    sntcrzlgna= Location(name='Santa Cruz La Laguna',location_type= 'municipality',parent= solo)
    sntcrzlgna.save()
    sntlucutatln= Location(name='Santa Lucía Utatlán',location_type= 'municipality',parent= solo)
    sntlucutatln.save()
    sntmriavctcion= Location(name='Santa María Visitación' ,location_type= 'municipality',parent= solo)
    sntmriavctcion.save()
    sntigoattlan= Location(name='Santiago Atitlán',location_type= 'municipality',parent= solo)
    sntigoattlan.save()
    solola= Location(name='Sololá',location_type= 'municipality',parent= solo)
    solola.save()
    print('Municipalities Solola done!')

    #Suchitepéquez
    chicacao= Location(name='Chicacao',location_type= 'municipality',parent= suchi)
    chicacao.save()
    cuyo= Location(name='Cuyotenango',location_type= 'municipality',parent= suchi)
    cuyo.save()
    mztenango= Location(name='Mazatenango',location_type= 'municipality',parent= suchi)
    mztenango.save()
    patulul= Location(name='Patulul',location_type= 'municipality',parent= suchi)
    patulul.save()
    pblonv= Location(name='Pueblo Nuevo',location_type= 'municipality',parent= suchi)
    pblonv.save()
    riobrvo= Location(name='Río Bravo' ,location_type= 'municipality',parent= suchi)
    riobrvo.save()
    samayac= Location(name='Samayac',location_type= 'municipality',parent= suchi)
    samayac.save()
    sntoniosuchi= Location(name='San Antonio Suchitepéquez',location_type= 'municipality',parent= suchi)
    sntoniosuchi.save()
    snbernardino= Location(name='San Bernardino',location_type= 'municipality',parent= suchi)
    snbernardino.save()
    snfrscozpttlan= Location(name='San Francisco Zapotitlán',location_type= 'municipality',parent= suchi)
    snfrscozpttlan.save()
    sngbriel= Location(name='San Gabriel',location_type= 'municipality',parent= suchi)
    sngbriel.save()
    snjselidolo= Location(name='San José El Idolo',location_type= 'municipality',parent= suchi)
    snjselidolo.save()
    snjselmaquina= Location(name='San José La Maquina',location_type= 'municipality',parent= suchi)
    snjselmaquina.save()
    snjnbautista= Location(name='San Juan Bautista',location_type= 'municipality',parent= suchi)
    snjnbautista.save()
    snlornzo= Location(name='San Lorenzo',location_type= 'municipality',parent= suchi)
    snlornzo.save()
    snmguelpanan= Location(name='San Miguel Panán',location_type= 'municipality',parent= suchi)
    snmguelpanan.save()
    snpablojcplas= Location(name='San Pablo Jocopilas',location_type= 'municipality',parent= suchi)
    snpablojcplas.save()
    sntabarbara= Location(name='Santa Bárbara',location_type= 'municipality',parent= suchi)
    sntabarbara.save()
    sntodmgosuchi= Location(name='Santo Domingo Suchitepéquez',location_type= 'municipality',parent= suchi)
    sntodmgosuchi.save()
    sntotmaslunion= Location(name='Santo Tomás La Unión' ,location_type= 'municipality',parent= suchi)
    sntotmaslunion.save()
    zunlito= Location(name='Zunilito',location_type= 'municipality',parent= suchi)
    zunlito.save()
    print('Municipalities Suchitepequez done!')

    #Totonicapán
    momostenango= Location(name='Momostenango',location_type= 'municipality',parent= toto)
    momostenango.save()
    sndresxecul= Location(name='San Andrés Xecul',location_type= 'municipality',parent= toto)
    sndresxecul.save()
    snbrtolo= Location(name='San Bartolo',location_type= 'municipality',parent= toto)
    snbrtolo.save()
    sncristoto= Location(name='San Cristóbal Totonicapán',location_type= 'municipality',parent= toto)
    sncristoto.save()
    snfrnscolalto= Location(name='San Francisco El Alto',location_type= 'municipality',parent= toto)
    snfrnscolalto.save()
    sntalcialreforma= Location(name='Santa Lucía La Reforma',location_type= 'municipality',parent= toto)
    sntalcialreforma.save()
    sntmriachiqui= Location(name='Santa María Chiquimula',location_type= 'municipality',parent= toto)
    sntmriachiqui.save()
    totonicapan= Location(name='Totonicapán',location_type= 'municipality',parent= toto)
    totonicapan.save()
    print('Municipalities Totonicapan done!')

    #Zacapa
    cabanas= Location(name='Cabañas',location_type= 'municipality',parent= zacapa)
    cabanas.save()
    estanzuela= Location(name='Estanzuela',location_type= 'municipality',parent= zacapa)
    estanzuela.save()
    gualan= Location(name='Gualán',location_type= 'municipality',parent= zacapa)
    gualan.save()
    huite= Location(name='Huité',location_type= 'municipality',parent= zacapa)
    huite.save()
    lunion= Location(name='La Unión',location_type= 'municipality',parent= zacapa)
    lunion.save()
    riondo= Location(name='Río Hondo',location_type= 'municipality',parent= zacapa)
    riondo.save()
    sndiego= Location(name='San Diego',location_type= 'municipality',parent= zacapa)
    sndiego.save()
    snjrge= Location(name='San Jorge',location_type= 'municipality',parent= zacapa)
    snjrge.save()
    teculutan= Location(name='Teculután',location_type= 'municipality',parent= zacapa)
    teculutan.save()
    usumatlan= Location(name='Usumatlán',location_type= 'municipality',parent= zacapa)
    usumatlan.save()
    zacapa= Location(name='Zacapa',location_type= 'municipality',parent= zacapa)
    zacapa.save()
    print('Municipalities Zacapa done!')

    #City
    gtCity = Location(name="Guatemala City", location_type="city", parent=gtDep)
    gtCity.save()
    sntaCatarinap = Location(name="Santa Catarina Pinula", location_type="city", parent=sntcatarinapnla)
    sntaCatarinap.save()
    snmiguelptpa = Location(name="San Miguel Petapa", location_type="city", parent=snmiguelptp)
    snmiguelptpa.save()
    mixcoct = Location(name="Mixco", location_type="city", parent=mixco)
    mixcoct.save()
    villanvact = Location(name="Villa Nueva", location_type="city", parent=villanva)
    villanvact.save()
    fraijanesct = Location(name="Fraijanes", location_type="city", parent=mfraijanes)
    fraijanesct.save()
    villacnls = Location(name="Villa Canales", location_type="city", parent=villacnles)
    villacnls.save()
    snjosep = Location(name="San José Pinula", location_type="city", parent=snjosepnla)
    snjosep.save()
    antigua = Location(name="Antigua Guatemala", location_type="city", parent=sacatpqz)
    antigua.save()
    snlucas = Location(name="San Lucas Sacatepéquez", location_type="city", parent=sacatpqz)
    snlucas.save()
    print('Cities are done!')

    #Zone
    z1= Location(name="zona 1", location_type="zone", parent=gtCity)
    z1.save()
    z2= Location(name="zona 2", location_type="zone", parent=gtCity)
    z2.save()
    z3= Location(name="zona 3", location_type="zone", parent=gtCity)
    z3.save()
    z4= Location(name="zona 4", location_type="zone", parent=gtCity)
    z4.save()
    z5= Location(name="zona 5", location_type="zone", parent=gtCity)
    z5.save()
    z6= Location(name="zona 6", location_type="zone", parent=gtCity)
    z6.save()
    z7= Location(name="zona 7", location_type="zone", parent=gtCity)
    z7.save()
    z8= Location(name="zona 8", location_type="zone", parent=gtCity)
    z8.save()
    z9= Location(name="zona 9", location_type="zone", parent=gtCity)
    z9.save()
    z10= Location(name="zona 10", location_type="zone", parent=gtCity)
    z10.save()
    z11= Location(name="zona 11", location_type="zone", parent=gtCity)
    z11.save()
    z12= Location(name="zona 12", location_type="zone", parent=gtCity)
    z12.save()
    z13= Location(name="zona 13", location_type="zone", parent=gtCity)
    z13.save()
    z14= Location(name="zona 14", location_type="zone", parent=gtCity)
    z14.save()
    z15= Location(name="zona 15", location_type="zone", parent=gtCity)
    z15.save()
    z16= Location(name="zona 16", location_type="zone", parent=gtCity)
    z16.save()
    z17= Location(name="zona 17", location_type="zone", parent=gtCity)
    z17.save()
    z18= Location(name="zona 18", location_type="zone", parent=gtCity)
    z18.save()
    z19= Location(name="zona 19", location_type="zone", parent=gtCity)
    z19.save()
    z20= Location(name="zona 20", location_type="zone", parent=gtCity)
    z20.save()
    z21= Location(name="zona 21", location_type="zone", parent=gtCity)
    z21.save()
    z22= Location(name="zona 22", location_type="zone", parent=gtCity)
    z22.save()
    z23= Location(name="zona 23", location_type="zone", parent=gtCity)
    z23.save()
    print('Zones are done!')


    # INSTITUTION:
    uvg = Institution(name="Universidad del Valle de Guatemala", institution_type="university", location= z15)
    uvg.save()
    url = Institution(name="Universidad Rafael Ladivar", institution_type="university", location= z16)
    url.save()
    ufm = Institution(name="Universidad Francisco Marroquín", institution_type="university", location= z10)
    ufm.save()
    print('Institutions are done!')

    #CAREER:
    computerscience = Career(name= "Ingeniería en Ciencias de la Computación y Tecnología de la Información", institution=uvg)
    computerscience.save()
    bioinformatica = Career(name= "Ingeniería Bioinformática", institution=uvg)
    bioinformatica.save()
    biomedica = Career(name= "Ingeniería Biomédica", institution=uvg)
    biomedica.save()
    biotecindus = Career(name= "Ingeniería Biotecnología Industrial", institution=uvg)
    biotecindus.save()
    alimentos = Career(name= "Ingeniería Ciencias de Alimentos", institution=uvg)
    alimentos.save()
    admin = Career(name= "Ingeniería Ciencia de la Administración", institution=uvg)
    admin.save()
    datos = Career(name= "Ingeniería Ciencia de los Datos", institution=uvg)
    datos.save()
    civil = Career(name= "Ingeniería Civil" , institution=uvg)
    civil.save()
    civilambiental = Career(name= "Ingeniería Civil Ambiental ", institution=uvg)
    civilambiental.save()
    civilarqu = Career(name= "Ingeniería Civil Arquitectónica", institution=uvg)
    civilarqu.save()
    civilindus = Career(name= "Ingeniería Civil Industrial" , institution=uvg)
    civilindus.save()
    electronica = Career(name= "Ingeniería Electrónica", institution=uvg)
    electronica.save()
    industrial = Career(name= "Ingeniería Industrial", institution=uvg)
    industrial.save()
    mecanica = Career(name= "Ingeniería Mecánica", institution=uvg)
    mecanica.save()
    mecaindus = Career(name= "Ingeniería Mecánica Industrial" , institution=uvg)
    mecaindus.save()
    mecatronica = Career(name= "Ingeniería Mecatrónica", institution=uvg)
    mecatronica.save()
    ingquimica = Career(name= "Ingeniería Química" , institution=uvg)
    ingquimica.save()
    quimindutrial = Career(name= "Ingeniería Química Industrial", institution=uvg)
    quimindutrial.save()
    businesmarketing= Career(name= "Food Business and Marketing", institution=uvg)
    businesmarketing.save()
    marketnbusiness= Career(name= "International Marketing and Business Analytics", institution=uvg)
    marketnbusiness.save()
    biologia= Career(name= "Biología" , institution=uvg)
    biologia.save()
    bioquimicro= Career(name= "Bioquímica y Microbiología ", institution=uvg)
    bioquimicro.save()
    biotecmole= Career(name= "Biotecnología Molecular", institution=uvg)
    biotecmole.save()
    comunicaletras= Career(name= "Comunicación y Letras", institution=uvg)
    comunicaletras.save()
    cfisica= Career(name= "Física ", institution=uvg)
    cfisica.save()
    mateaplicada= Career(name= "Matemática Aplicada", institution=uvg)
    mateaplicada.save()
    nutri= Career(name= "Nutrición", institution=uvg)
    nutri.save()
    quimi= Career(name= "Química", institution=uvg)
    quimi.save()
    quimifar= Career(name= "Química Farmacéutica", institution=uvg)
    quimifar.save()
    antrosocio= Career(name= "Antropología y Sociología", institution=uvg)
    antrosocio.save()
    arqueologia= Career(name= "Arqueología", institution=uvg)
    arqueologia.save()
    psicologia= Career(name= "Psicología", institution=uvg)
    psicologia.save()
    artsglovaraffairs= Career(name= "Relaciones Internacionales & Master of Arts in Global Affairs", institution=uvg)
    artsglovaraffairs.save()
    pruduccionmusical= Career(name= "Composición y Producción Musical", institution=uvg)
    pruduccionmusical.save()
    innoviacion= Career(name= "Diseño de Producto e Innovación", institution=uvg)
    innoviacion.save()
    licedu= Career(name= "Licenciatura en Educación", institution=uvg)
    licedu.save()
    edubioqui= Career(name= "Profesorado y Licenciatura en Educación con Especialidad en Ciencias Biológicas y Químicas", institution=uvg)
    edubioqui.save()
    educienciaso= Career(name= "Profesorado y Licenciatura en Educación con Especialidad en Ciencias Sociales", institution=uvg)
    educienciaso.save()
    edulenguaje= Career(name= "Profesorado y Licenciatura en Educación con Especialidad en Comunicación y Lenguaje", institution=uvg)
    edulenguaje.save()
    eduinclusiva= Career(name= "Profesorado y Licenciatura en Educación con Especialidad en Educación Inclusiva", institution=uvg)
    eduinclusiva.save()
    edumusica= Career(name= "Profesorado y Licenciatura en Educación con Especialidad en Educación Musical", institution=uvg)
    edumusica.save()
    eduprimaria= Career(name= "Profesorado y Licenciatura en Educación con Especialidad en Educación Primaria", institution=uvg)
    eduprimaria.save()
    eduenglish= Career(name= "Profesorado y Licenciatura en Educación con Especialidad en English Language Teaching", institution=uvg)
    eduenglish.save()
    educomunidad= Career(name= "Profesorado y Licenciatura en Educación con Especialidad en Matemática y Ciencias FísicasProgramas de Actualización para la Comunidad Educativa", institution=uvg)
    educomunidad.save()
    print('Careers are done!')

    #COURSE
    csdvida = Course(name= "Ciencias de la Vida", institution=uvg)
    csdvida.save()
    ecuasdif = Course(name= "Ecuasiones Diferenciales", institution=uvg)
    ecuasdif.save()
    algyprograbasic = Course(name= "Algoritmos y Programación Básica ", institution=uvg)
    algyprograbasic.save()
    pensacuanti = Course(name= "Pensamiento Cuantitativo", institution=uvg)
    pensacuanti.save()
    comefec = Course(name= "Comunicación Efectiva", institution=uvg)
    comefec.save()
    quimigene = Course(name= "Química General", institution=uvg)
    quimigene.save()
    introinge = Course(name= "Introducción a la Ingeniería", institution=uvg)
    introinge.save()
    prograoo = Course(name= "Programación Orientada a Objetos", institution=uvg)
    prograoo.save()
    stdstica = Course(name= "Estadística 1", institution=uvg)
    stdstica.save()
    ciudadniagbl = Course(name= "Ciudadanía Global", institution=uvg)
    ciudadniagbl.save()
    fisica1 = Course(name= "Física 1", institution=uvg)
    fisica1.save()
    calculo1 = Course(name= "Cálculo 1", institution=uvg)
    calculo1.save()
    alglineal1 = Course(name= "Algebra Lineal 1", institution=uvg)
    alglineal1.save()
    orgdcmpass = Course(name= "Organización de Computadoras y Assembler", institution=uvg)
    orgdcmpass.save()
    fisica2 = Course(name= "Física 2", institution=uvg)
    fisica2.save()
    calculo2 = Course(name= "Cálculo 2", institution=uvg)
    calculo2.save()
    appsyjuegs = Course(name= "Programación de Plataformas Móviles y Juegos", institution=uvg)
    appsyjuegs.save()
    algydtos = Course(name= "Algoritmos y Estructuras de Datos", institution=uvg)
    algydtos.save()
    gtcntxtmuni = Course(name= "Guatemala en el Contexto Mundial", institution=uvg)
    gtcntxtmuni.save()
    fisica3 = Course(name= "Física 3", institution=uvg)
    fisica3.save()
    matedis = Course(name= "Matemática Discreta 1", institution=uvg)
    matedis.save()
    retos = Course(name= "Retos Ambientales y Sostenibilidad", institution=uvg)
    retos.save()
    ipc = Course(name= "Investigación y Pensamiento Científico", institution=uvg)
    ipc.save()
    pdmicro = Course(name= "Programación de Microprocesadores", institution=uvg)
    pdmicro.save()
    emprendimiento = Course(name= "Emprendimiento e Innovación", institution=uvg)
    emprendimiento.save()
    db = Course(name= "Bases de Datos", institution=uvg)
    db.save()
    ingsftwr1 = Course(name= "Ingeniería en Software 1", institution=uvg)
    ingsftwr1.save()
    stw = Course(name= "Sistemas y Tecnologías Web", institution=uvg)
    stw.save()
    ihc = Course(name= "Interacción Humano Computador", institution=uvg)
    ihc.save()
    slctvodsrollopro = Course(name= "Selectivo de Desarrollo Profesional", institution=uvg)
    slctvodsrollopro.save()
    ingsftwr2 = Course(name= "Ingeniería de Software 2", institution=uvg)
    ingsftwr2.save()
    grfscompu = Course(name= "Gráficas por Computadora", institution=uvg)
    grfscompu.save()
    logicamt = Course(name= "Lógica Matemática", institution=uvg)
    logicamt.save()
    ai = Course(name= "Inteligencia Artificial", institution=uvg)
    ai.save()
    dtm = Course(name= "Minería de Datos", institution=uvg)
    dtm.save()
    ada = Course(name= "Análisis y Diseño de Algoritmos", institution=uvg)
    ada.save()
    sistoperativos = Course(name= "Sistemas Operativos", institution=uvg)
    sistoperativos.save()
    dant = Course(name= "Desarrollo Ágil de Negocios Tecnológicos", institution=uvg)
    dant.save()
    apti = Course(name= "Administración de Proyectos de TI", institution=uvg)
    apti.save()
    dtscins1 = Course(name= "Data Science 1", institution=uvg)
    dtscins1.save()
    redes = Course(name= "Redes", institution=uvg)
    redes.save()
    arqemp = Course(name= "Arquitectura Empresarial", institution=uvg)
    arqemp.save()
    mdlsimu = Course(name= "Modelación y Simulación", institution=uvg)
    mdlsimu.save()
    dii = Course(name= "Diseño e Innovación en Ingeniería 1", institution=uvg)
    dii.save()
    cpd = Course(name= "Computación Paralela y Distribuida", institution=uvg)
    cpd.save()
    practicas = Course(name= "Práctica Profesional", institution=uvg)
    practicas.save()
    dlp = Course(name= "Diseño de Lenguajes de Programación", institution=uvg)
    dlp.save()
    ssc = Course(name= "Seguridad en Sistemas de Computación", institution=uvg)
    ssc.save()
    ams = Course(name= "Administración y Mantenimiento Sistem ", institution=uvg)
    ams.save()
    constcompi = Course(name= "Construcción de Compiladores", institution=uvg)
    constcompi.save()
    plancomp = Course(name= "Planeación de Compiladores", institution=uvg)
    plancomp.save()
    peo = Course(name= "Planeación Estratégica y Operacional", institution=uvg)
    peo.save()
    dii2 = Course(name= "Diseño e Innovación en Ingeniería 2", institution=uvg)
    dii2.save()
    teoprob = Course(name= "Teoría de Probabilidades", institution=uvg)
    teoprob.save()
    sds = Course(name= "Security Data Science", institution=uvg)
    sds.save()
    print('Courses are done!')

    #SUBJECT
    mate = Subject(name= "Matemáticas")
    mate.save()
    quimica = Subject(name= "Química")
    quimica.save()
    fisica = Subject(name= "Física")
    fisica.save()
    biolo = Subject(name= "Biología")
    biolo.save()
    compu = Subject(name= "Computación")
    compu.save()
    arte = Subject(name= "Arte")
    arte.save()
    filo = Subject(name= "Filisofía")
    filo.save()
    psico = Subject(name= "Psicología")
    psico.save()
    print('Subjects are done!')

    #TOPIC
    algebra = Topic(name= "Álgebra", subject= mate)
    algebra.save()
    trigo = Topic(name= "Trigonometría", subject= mate)
    trigo.save()
    aritmetica = Topic(name= "Aritmética", subject= mate)
    aritmetica.save()
    entalpia = Topic(name= "Entalpía", subject= quimica)
    entalpia.save()
    reacc = Topic(name= "Reacciones", subject= quimica)
    reacc.save()
    quimiorg = Topic(name= "Química orgánica", subject= quimica)
    quimiorg.save()
    estquimi = Topic(name= "Estéreo química", subject= quimica)
    estquimi.save()
    tiropbolico = Topic(name= "Tiro parabólico", subject= fisica)
    tiropbolico.save()
    mcu = Topic(name= "Movimiento circular uniforme", subject= fisica)
    mcu.save()
    cmposmgnticos = Topic(name= "Campos magneticos", subject= fisica)
    cmposmgnticos.save()
    mru = Topic(name= "Movimiento rectilineo uniforme", subject= fisica)
    mru.save()
    reprocel = Topic(name= "Reproducción celular", subject= biolo)
    reprocel.save()
    gene = Topic(name= "Genética básica", subject= biolo)
    gene.save()
    evo = Topic(name= "Evolución", subject= biolo)
    evo.save()
    proti = Topic(name= "Protista", subject= biolo)
    proti.save()
    nvorg = Topic(name= "Niveles de organización", subject= biolo)
    nvorg.save()
    sischum = Topic(name= "Sistemas del cuerpo humano", subject= biolo)
    sischum.save()
    bd = Topic(name= "Bases de Datos", subject= compu)
    bd.save()
    pw = Topic(name= "Programación Web", subject= compu)
    pw.save()
    poo = Topic(name= "Programación orientada a objetos", subject= compu)
    poo.save()
    arcont = Topic(name= "Arte Contemporáneo", subject= arte)
    arcont.save()
    corvan = Topic(name= "Corrientes vanguardistas", subject= arte)
    corvan.save()
    retratos = Topic(name= "Retratos", subject= arte)
    retratos.save()
    tdv = Topic(name= "Tablas de verdad", subject= filo)
    tdv.save()
    mhd = Topic(name= "Método hipotético deductivo", subject= filo)
    mhd.save()
    realidad = Topic(name= "La realidad", subject= filo)
    realidad.save()
    neurosc = Topic(name= "Neurociencias", subject= psico)
    neurosc.save()
    procog = Topic(name= "Procesos Cognitivos", subject= psico)
    procog.save()
    evapsico = Topic(name= "Evaluación Psicológica", subject= psico)
    evapsico.save()
    print('Topics are done!')

    #LANGUAGE
    spanish= Language(name= "Español")
    spanish.save()
    english= Language(name= "English")
    english.save()
    print('Languages are done!')

    #USER
    admin= User(username="admin", first_name = "Aministrador", last_name="Apellido",email="admin@admin.com", is_superuser = True, is_staff = True)
    admin.set_password("admin")
    admin.save()

    jgblock= User(username="JBlock",first_name="José Gabriel", last_name="Block Staackmann",email="blockmann3@gmail.com")
    jgblock.set_password("admin")
    jgblock.save()

    marcfuents= User(username="Marco",first_name="Marco José", last_name="Fuentes Lima",email="fue18188@uvg.edu.gt")
    marcfuents.set_password("admin")
    marcfuents.save()

    andy= User(username="Andy",first_name="Andy", last_name="Castillo",email="cas18040@uvg.edu.gt")
    andy.set_password("admin")
    andy.save()

    willi= User(username="Willi",first_name="Francisco", last_name="Rosal",email="ros18676@uvg.edu.gt")
    willi.set_password("Admin")
    willi.save()

    luca= User(username="Luca",first_name="Gian Luca", last_name="Rivera",email="riv18049@uvg.edu.gt")
    luca.set_password("admin")
    luca.save()
    print('Users are done!')

    #USER DETAIL
    admindetail = UserDetail(user_ptr= admin,birthdate="1999-12-29", language= spanish, phone= "66666666", gender="M", is_tutor= False, institution= uvg, career= computerscience, location= z15)
    admindetail.save_base(raw=True)

    joseblock = UserDetail(user_ptr= jgblock,birthdate="1999-12-29", language= spanish, phone= "59300498", gender="M", is_tutor= False, institution= uvg, career= computerscience, location= z15)
    joseblock.save_base(raw=True)

    marcofuentes = UserDetail(user_ptr= marcfuents,birthdate="1999-7-16", language= spanish, phone= "54131389", gender="M", is_tutor= True, institution= uvg, career= computerscience, location= mixco)
    marcofuentes.save_base(raw=True)

    andycas = UserDetail(user_ptr= andy,birthdate="1999-09-21", language= spanish, phone= "59300498", gender="M", is_tutor= False, institution= uvg, career= computerscience, location= mixco)
    andycas.save_base(raw=True)

    williros = UserDetail(user_ptr= willi,birthdate="1998-12-17", language= spanish, phone= "59300498", gender="M", is_tutor= False, institution= uvg, career= computerscience, location= z15)
    williros.save_base(raw=True)

    lucariv = UserDetail(user_ptr= luca,birthdate="1999-10-11", language= spanish, phone= "59300498", gender="M", is_tutor= False, institution= uvg, career= computerscience, location=snlcssctpqz)
    lucariv.save_base(raw=True)

    print('User Details are done!')

    #TUTOR
    tutormarcfuent= Tutor(user_ptr=marcfuents, description="Hola soy Marco", individual_price= 100, grupal_price=50)
    tutormarcfuent.save_base(raw=True)
    print('Tutors are done!')

    #SCHEDULES
    schfuentesmarcos = Schedule(user=marcfuents)
    schfuentesmarcos.save()
    print('Schedules are done!')

    #PERIODS
    periodmarcfuent1 = Period(schedule=schfuentesmarcos, day="Saturday", start_time= "11:00", end_time= "12:00")
    periodmarcfuent1.save()
    periodmarcfuent2 = Period(schedule=schfuentesmarcos, day="Saturday", start_time= "15:00", end_time= "16:00")
    periodmarcfuent2.save()
    periodmarcfuent3 = Period(schedule=schfuentesmarcos, day="Saturday", start_time= "17:00", end_time= "18:00")
    periodmarcfuent3.save()
    periodmarcfuent4 = Period(schedule=schfuentesmarcos, day="Sunday", start_time= "10:00", end_time= "11:00")
    periodmarcfuent4.save()
    periodmarcfuent5 = Period(schedule=schfuentesmarcos, day="Sunday", start_time= "15:00", end_time= "16:00")
    periodmarcfuent5.save()
    print('Periods are done!')

    #WORKFLOW
    wftutoria= Workflow(name= "Tutoría workflow")
    wftutoria.save()
    print('Workflows are done!')

    #STATUS
    ststutoria5= Status(name="end", is_initial=False, is_final=True, workflow=wftutoria)
    ststutoria5.save()
    ststutoria4= Status(name="canceled", is_initial=False, is_final=True, workflow=wftutoria)
    ststutoria4.save()
    ststutoria3= Status(name="in_process", is_initial=False, is_final=False, workflow=wftutoria)
    ststutoria3.save()
    ststutoria2= Status(name="scheduled", is_initial=False, is_final=False, workflow=wftutoria)
    ststutoria2.save()
    print('Statuses are done!')

    #TUTORIA
    tutoria1 = Tutoria.objects.create(tutor=marcfuents, tutorado=jgblock, total_price=100, datetime='2020-05-21 13:00', course=fisica3)
    tutoria2 = Tutoria.objects.create(tutor=marcfuents, tutorado=andy, total_price=100, datetime='2020-08-25 17:00', status=ststutoria2, course=ipc)
    tutoria3 = Tutoria.objects.create(tutor=marcfuents, tutorado=willi, total_price=100, datetime='2020-08-25 20:00', status=ststutoria4, course=gtcntxtmuni)
    tutoria4 = Tutoria.objects.create(tutor=marcfuents, tutorado=luca, total_price=100, datetime='2020-08-25 19:30', status=ststutoria3, course=fisica3)
    tutoria5 = Tutoria.objects.create(tutor=marcfuents, tutorado=willi, total_price=100, datetime='2020-08-25 13:30', status=ststutoria2, course=stdstica)
    print('Tutorias are done!')

    #NOTIFICATION
    noti1= Notification(title="Init Notification", description="Esto es una notificacion prueba, esperamos un buen funcionamiento.", date='2020-10-28 23:58', user=willi)
    noti1.save()
    print('Notifications are done!')
    
    data= {
        'Status': 'Ok',
        'Data': 'Data imported'
    }
    return JsonResponse(data)

