# Generated by Django 3.0.5 on 2020-08-19 02:10

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('institutions', '0002_auto_20200510_2225'),
        ('subjects', '0002_auto_20200510_2228'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0002_auto_20200510_2334'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('score', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('description', models.CharField(max_length=200, null=True)),
                ('hours_done', models.PositiveIntegerField(default=0)),
                ('individual_price', models.DecimalField(decimal_places=2, default=80.0, max_digits=6)),
                ('grupal_price', models.DecimalField(decimal_places=2, default=40.0, max_digits=6)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.TimeField()),
                ('hours', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.Course')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Location')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='workflows.Status')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.Topic')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tutorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
