# Generated by Django 3.0.5 on 2020-05-24 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoria',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutoria',
            name='tutorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorado', to=settings.AUTH_USER_MODEL),
        ),
    ]
